-- 코드를 입력하세요
SELECT A.AUTHOR_ID, AUTHOR.AUTHOR_NAME, A.CATEGORY, A.TOTAL_SALES 
FROM
(SELECT CATEGORY, AUTHOR_ID, SUM(SALES * PRICE) TOTAL_SALES
FROM BOOK, BOOK_SALES
WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID 
AND TO_CHAR(SALES_DATE, 'YYYYMM') = 202201
GROUP BY CATEGORY, AUTHOR_ID) A, AUTHOR
WHERE A.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY A.AUTHOR_ID, A.CATEGORY DESC;