-- 코드를 작성해주세요
WITH RECURSIVE GenerationCTE AS (
    
    SELECT 
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 
        E1.ID,
        E1.PARENT_ID,
        E2.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA E1
    JOIN GenerationCTE E2
    ON E1.PARENT_ID = E2.ID
)

SELECT 
    COUNT(E1.GENERATION) AS COUNT,
    E1.GENERATION
FROM GenerationCTE E1
LEFT JOIN GenerationCTE E2
ON E1.ID = E2.PARENT_ID
WHERE E2.ID IS NULL
GROUP BY E1.GENERATION
HAVING E1.GENERATION
;