-- 코드를 입력하세요
SELECT 
    T1.CAR_ID, 
    CASE
        WHEN T2.CAR_ID IS NULL THEN '대여 가능'
        ELSE '대여중'
    END AS AVAILABILITY
FROM (
    SELECT HISTORY_ID, CAR_ID 
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID) T1
LEFT JOIN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-10-16'
    AND '2022-10-16' <= END_DATE) T2
ON T1.CAR_ID = T2.CAR_ID
ORDER BY T1.CAR_ID DESC