-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, B.TOTAL_SALES
FROM FOOD_PRODUCT A, 
(SELECT P.PRODUCT_ID, SUM(P.PRICE * O.AMOUNT) TOTAL_SALES
FROM FOOD_PRODUCT P, FOOD_ORDER O
WHERE P.PRODUCT_ID = O.PRODUCT_ID 
AND TO_CHAR(O.PRODUCE_DATE, 'YYYYMM') = '202205'
GROUP BY P.PRODUCT_ID) B
WHERE A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, A.PRODUCT_ID;