-- 코드를 입력하세요

-- SELECT *
-- FROM USED_GOODS_BOARD
-- WHERE TO_CHAR(CREATED_DATE, 'YYYYMM') = '202210';

-- SELECT *
-- FROM USED_GOODS_REPLY;

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, 
TO_CHAR(R.CREATED_DATE, 'YYYY-MM-DD') 
FROM USED_GOODS_BOARD B, USED_GOODS_REPLY R
WHERE B.BOARD_ID = R.BOARD_ID AND TO_CHAR(B.CREATED_DATE, 'YYYYMM') = '202210'
ORDER BY R.CREATED_DATE, B.TITLE;
