-- 코드를 입력하세요
SELECT A.MEMBER_ID, A.MEMBER_NAME, A.GENDER, DATE_FORMAT(A.DATE_OF_BIRTH, '%Y-%m-%d') DATE_OF_BIRTH
FROM MEMBER_PROFILE A
WHERE MONTH(A.DATE_OF_BIRTH) = 3
AND A.TLNO IS NOT NULL
AND A.GENDER = 'W'
ORDER BY A.MEMBER_ID;