-- 코드를 입력하세요
SELECT 
    T2.USER_ID,
    T2.NICKNAME,
    T1.TOTAL_SALES
FROM (
    SELECT 
        WRITER_ID,
        SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD T1
    WHERE T1.STATUS = 'DONE'
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000) T1
JOIN USED_GOODS_USER T2
ON T1.WRITER_ID = T2.USER_ID
ORDER BY TOTAL_SALES
;

