WITH REVIEW_COUNT AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_REVIEWER AS (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE REVIEW_CNT = (SELECT MAX(REVIEW_CNT) FROM REVIEW_COUNT)
)
SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW RR
JOIN MEMBER_PROFILE MP ON RR.MEMBER_ID = MP.MEMBER_ID
WHERE RR.MEMBER_ID IN (SELECT MEMBER_ID FROM MAX_REVIEWER)
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC;
