-- 코드를 입력하세요
-- 상관쿼리 사용
-- SELECT FLAVOR 
-- FROM FIRST_HALF FH
-- WHERE TOTAL_ORDER > 3000 
-- AND (SELECT INGREDIENT_TYPE FROM ICECREAM_INFO WHERE FLAVOR = FH.FLAVOR)
-- = 'fruit_based'
-- ORDER BY TOTAL_ORDER DESC;

select FIRST_HALF.FLAVOR
from FIRST_HALF
join ICECREAM_INFO
on FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
where FIRST_HALF.TOTAL_ORDER > 3000
and ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'
order by TOTAL_ORDER DESC;
