-- 코드를 작성해주세요
SELECT 
    SUM(T2.SCORE) AS SCORE, 
    T1.EMP_NO,
    T1.EMP_NAME,
    T1.POSITION,
    T1.EMAIL
FROM HR_EMPLOYEES T1
JOIN HR_GRADE T2
ON T1.EMP_NO = T2.EMP_NO
GROUP BY T1.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
;

