-- 코드를 작성해주세요
SELECT 
    SUM(T2.SCORE) AS SCORE, 
    T1.EMP_NO,
    T1.EMP_NAME,
    T1.POSITION,
    T1.EMAIL
FROM HR_EMPLOYEES T1
JOIN HR_GRADE T2
ON T1.EMP_NO = T2.EMP_NO
GROUP BY T1.EMP_NO
ORDER BY SCORE DESC
LIMIT 1
;

-- 윈도우함수 활용법
# SELECT 
#     TotalScores.SCORE, 
#     E.EMP_NO,
#     E.EMP_NAME,
#     E.POSITION,
#     E.EMAIL
# FROM (
#     SELECT 
#         G.EMP_NO,
#         SUM(G.SCORE) AS SCORE,
#         ROW_NUMBER() OVER (ORDER BY SUM(G.SCORE) DESC) AS RN
#     FROM HR_GRADE G
#     WHERE G.YEAR = 2022
#     GROUP BY G.EMP_NO
# ) TotalScores
# JOIN HR_EMPLOYEES E
#     ON TotalScores.EMP_NO = E.EMP_NO
# WHERE TotalScores.RN = 1;
