-- 코드를 입력하세요
SELECT T1.CATEGORY, T1.MAX_PRICE, T2.PRODUCT_NAME
FROM (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY) T1
JOIN FOOD_PRODUCT T2
ON T1.CATEGORY = T2.CATEGORY
AND T1.MAX_PRICE = T2.PRICE
WHERE T1.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY T1.MAX_PRICE DESC
;

-- 1. 윈도우함수 사용
# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM (
#     SELECT CATEGORY, PRICE, PRODUCT_NAME,
#            RANK() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKING
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
# ) T
# WHERE RANKING = 1
# ORDER BY MAX_PRICE DESC;


-- 2. 서브쿼리로 조건 필터링
# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
# FROM FOOD_PRODUCT
# WHERE (CATEGORY, PRICE) IN (
#     SELECT CATEGORY, MAX(PRICE)
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#     GROUP BY CATEGORY
# )
# ORDER BY MAX_PRICE DESC;


-- 3. SELF-JOIN 사용
# SELECT A.CATEGORY, A.PRICE AS MAX_PRICE, A.PRODUCT_NAME
# FROM FOOD_PRODUCT A
# LEFT JOIN FOOD_PRODUCT B
#   ON A.CATEGORY = B.CATEGORY AND A.PRICE < B.PRICE
# WHERE B.CATEGORY IS NULL
# AND A.CATEGORY IN ('과자', '국', '김치', '식용유')
# ORDER BY MAX_PRICE DESC;


-- 4. CTE(Common Table Expression) 활용
# WITH MaxPriceByCategory AS (
#     SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
#     FROM FOOD_PRODUCT
#     WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
#     GROUP BY CATEGORY
# )
# SELECT M.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
# FROM MaxPriceByCategory M
# JOIN FOOD_PRODUCT F
# ON M.CATEGORY = F.CATEGORY AND M.MAX_PRICE = F.PRICE
# ORDER BY M.MAX_PRICE DESC;