-- 코드를 작성해주세요
SELECT
     COUNT(*) AS FISH_COUNT
    ,MAX(LENGTH) AS MAX_LENGTH
    ,T1.FISH_TYPE
FROM FISH_INFO T1
JOIN (
    SELECT
        FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING AVG(COALESCE(LENGTH,10)) >= 33
) T2
ON T1.FISH_TYPE = T2.FISH_TYPE
GROUP BY T1.FISH_TYPE
ORDER BY T1.FISH_TYPE